### PR TITLE
Automated update

### PR DESCRIPTION
**Pull request by infinixbot**
<details><summary>cargo changes</summary>

### cargo upgrade

```
    Checking nixpkgs-vet's dependencies
name       old req compatible latest  new req
====       ======= ========== ======  =======
serde_json 1.0.128 1.0.132    1.0.132 1.0.132
serde      1.0.210 1.0.213    1.0.213 1.0.213
   Upgrading recursive dependencies
     Locking 0 packages to latest compatible versions
note: pass `--verbose` to see 10 unchanged dependencies behind latest
note: Re-run with `--verbose` to show more dependencies
  latest: 17 packages

```
### cargo update

```
    Updating crates.io index
     Locking 3 packages to latest compatible versions
    Updating anyhow v1.0.89 -> v1.0.91
    Updating libc v0.2.159 -> v0.2.161
    Updating proc-macro2 v1.0.87 -> v1.0.89
note: pass `--verbose` to see 14 unchanged dependencies behind latest

```
### cargo outdated

```
All dependencies are up to date, yay!

```
### cargo audit

```
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 664 security advisories (from /home/runner/.cargo/advisory-db)
    Updating crates.io index
    Scanning repo/Cargo.lock for vulnerabilities (91 crate dependencies)

```
</details>
<details><summary>GitHub Action updates</summary>

</details>
<details><summary>npins changes</summary>

```
[INFO ] Updating 'nixpkgs' …
Changes:
-    url: https://releases.nixos.org/nixpkgs/nixpkgs-24.11pre691017.b69de56fac8c/nixexprs.tar.xz
+    url: https://releases.nixos.org/nixpkgs/nixpkgs-24.11pre695900.782740762fb2/nixexprs.tar.xz
-    hash: 0z32pj0lh5ng2a6cn0qfmka8cynnygckn5615mkaxq2aplkvgzx3
+    hash: 0gg9jkp7iq531m8520ldnng2731s3ab3wdw34yb7rw0fsg4ncxz0
[INFO ] Updating 'treefmt-nix' …
Changes:
-    revision: 4446c7a6fc0775df028c5a3f6727945ba8400e64
+    revision: aac86347fb5063960eccb19493e0cadcdb4205ca
-    url: https://github.com/numtide/treefmt-nix/archive/4446c7a6fc0775df028c5a3f6727945ba8400e64.tar.gz
+    url: https://github.com/numtide/treefmt-nix/archive/aac86347fb5063960eccb19493e0cadcdb4205ca.tar.gz
-    hash: 0xyh9lwfvflagq7rk7cwbq41gx9f9s37s6kljp3wl3r860hnm566
+    hash: 0ysg99zcbq50ghjyqfkd6qkjdh74vn2ikv817rgp9mfnhfwayqsw
[INFO ] Update successful.
```
</details>

### CODE REVIEW

**Review by philiptaron — APPROVED** [review]
I'm pretty sure that the update github actions one isn't detecting new releases correctly, @infinisil.

**Comment by philiptaron** [comment]
It also looks like a new clippy found issues! Great.

**Comment by willbush** [comment]
I made another PR to fix clippy issues. Guessing there's no way for us to push on [infinixbot:auto-update](https://github.com/infinixbot/nixpkgs-check-by-name/tree/auto-update)?

**Comment by infinisil** [comment]
@willbush It should work if you go to https://github.com/NixOS/nixpkgs-vet/actions/workflows/update.yml and click "Run workflow", try it out :D

**Pull request merged**
