### PR TITLE
Number every problem reported by `nixpkgs-vet`

### PR DESCRIPTION
**Pull request by philiptaron**
## Motivation for changes

- #99 

## Description of changes

- [x] Make a struct for each error reported by `nixpkgs-vet`
- [x] Have it `Display` with the exact same error as previously
- [x] Change call site to report the specific error rather than use a `to_validation` closure

This PR is best reviewed commit-by-commit.

### CODE REVIEW

**Comment by willbush** [comment]
I'll get a chance to look at this closer tomorrow or this weekend

**Comment by philiptaron** [comment]
Gentle ping to review if you've got the cycles to spend.

**Comment by willbush** [comment]
Sorry for the wait! Seems like good changes all around to me. More widespread usage of `Into` trait and additional crates make a lot of sense. Really appreciate you breaking this commits up (looks like a lot of work). Only nit for future reference `fn read_dir_sorted` got moved and changed in the same commit it's easy to miss that it was changed at all. :)

**Review by willbush — APPROVED** [review]

**Comment by infinisil** [comment]
Nice work @philiptaron, and thanks for reviewing @willbush! Sorry that I'm not very available recently :sweat_smile:

**Pull request merged**
